### ISSUE TITLE
Incompatibility with sinatra 2

### ISSUE THREAD

**Issue by kamaradclimber** [rkh/sinatra-advanced-routes#11]
When using sinitra 2, simplying requiring sinatra advanced routes lead to stackoverflow.

```
require 'sinatra'
require 'sinatra/advanced_routes
```

leads to:

```
(eval):2:in `method_missing': stack level too deep (SystemStackError)
	from (eval):2:in `method_missing'
	from (eval):2:in `method_missing'
	from (eval):2:in `method_missing'
	from (eval):2:in `method_missing'
	from (eval):2:in `method_missing'
	from (eval):2:in `method_missing'
	from (eval):2:in `method_missing'
	from (eval):2:in `method_missing'
	 ... 1349 levels...
	from /home/g_seux/.gem/ruby/2.4.0/gems/sinatra-advanced-routes-0.4.1/lib/sinatra/advanced_routes.rb:2:in `require'
	from /home/g_seux/.gem/ruby/2.4.0/gems/sinatra-advanced-routes-0.4.1/lib/sinatra/advanced_routes.rb:2:in `<top (required)>'
	from bin/reproduce.rb:2:in `require'
	from bin/reproduce.rb:2:in `<main>'
```

**Comment by kamaradclimber** [comment]
It happens with 0.4.1, because 0.5.3 constrains sinatra version to ~>1.0

**Comment by kamaradclimber** [comment]
So this issue is more than advanced-routes does not support sinatra 2

**Comment by scalp42** [comment]
@rkh any chance you could take a look at this? 🙇

**Comment by pixeline** [comment]
@rkh This warning might point to the issue: 

`(eval):1: warning: redefining Object#method_missing may cause infinite loop`

**Comment by rkh** [comment]
Sorry, I don't think I'll have time to focus on this. I haven't used this library myself in years. If anyone wants to have a look at it, happy to do a quick review and possibly hand out commit access.
